//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordScrambleClientJS.WordScrambleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/WordScrambleGameJS")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scrambledWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unscrambledWordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scrambledWord {
            get {
                return this.scrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.scrambledWordField, value) != true)) {
                    this.scrambledWordField = value;
                    this.RaisePropertyChanged("scrambledWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unscrambledWord {
            get {
                return this.unscrambledWordField;
            }
            set {
                if ((object.ReferenceEquals(this.unscrambledWordField, value) != true)) {
                    this.unscrambledWordField = value;
                    this.RaisePropertyChanged("unscrambledWord");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordScrambleService.IWordScrambleService")]
    public interface IWordScrambleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleService/GetScrambledWord", ReplyAction="http://tempuri.org/IWordScrambleService/GetScrambledWordResponse")]
        WordScrambleClientJS.WordScrambleService.Word GetScrambledWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleService/GetScrambledWord", ReplyAction="http://tempuri.org/IWordScrambleService/GetScrambledWordResponse")]
        System.Threading.Tasks.Task<WordScrambleClientJS.WordScrambleService.Word> GetScrambledWordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleService/GuessWord", ReplyAction="http://tempuri.org/IWordScrambleService/GuessWordResponse")]
        bool GuessWord(string guessedWord, string encryptedUnscrambledWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordScrambleService/GuessWord", ReplyAction="http://tempuri.org/IWordScrambleService/GuessWordResponse")]
        System.Threading.Tasks.Task<bool> GuessWordAsync(string guessedWord, string encryptedUnscrambledWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordScrambleServiceChannel : WordScrambleClientJS.WordScrambleService.IWordScrambleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordScrambleServiceClient : System.ServiceModel.ClientBase<WordScrambleClientJS.WordScrambleService.IWordScrambleService>, WordScrambleClientJS.WordScrambleService.IWordScrambleService {
        
        public WordScrambleServiceClient() {
        }
        
        public WordScrambleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordScrambleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordScrambleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WordScrambleClientJS.WordScrambleService.Word GetScrambledWord() {
            return base.Channel.GetScrambledWord();
        }
        
        public System.Threading.Tasks.Task<WordScrambleClientJS.WordScrambleService.Word> GetScrambledWordAsync() {
            return base.Channel.GetScrambledWordAsync();
        }
        
        public bool GuessWord(string guessedWord, string encryptedUnscrambledWord) {
            return base.Channel.GuessWord(guessedWord, encryptedUnscrambledWord);
        }
        
        public System.Threading.Tasks.Task<bool> GuessWordAsync(string guessedWord, string encryptedUnscrambledWord) {
            return base.Channel.GuessWordAsync(guessedWord, encryptedUnscrambledWord);
        }
    }
}
